apiVersion: v1
kind: Service
metadata:
  name: fresheats-service
  namespace: fresheats-ns
  labels:
    app: fresheats
spec:
  type: LoadBalancer
  selector:
    app: fresheats
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
